name: build GOAMD64=v1 version of talos

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  build-release:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - run: |
          poetry install
          poetry run build.py --version ${{ inputs.version }}
