name: build GOAMD64=v1 version of talos

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Talos version

jobs:
  build-release:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: |
          set -e
          
          # exit early if the version does not exist
          curl https://api.github.com/repos/siderolabs/talos/releases/tags/v${{ inputs.version }} \
            --output /dev/null \
            --silent \
            --fail
          
          git clone --branch v${{ inputs.version }} --depth 1 https://github.com/siderolabs/talos.git ./talos.git
          cd ./talos.git && make all GOAMD64=v1 USERNAME=djeebus PUSH=true

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ./talos.git/_out/*            

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./talos.git/_out/*"
          body: "# v${{ inputs.version }}"
          commit: "main"
          replacesArtifacts: true
          tag: "${{ inputs.version }}"
