name: build GOAMD64=v1 version of talos

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Talos version

jobs:
  build-release:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - shell: bash
        run: |
          set -e
          
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io --username ${{ github.actor }} --password-stdin  
          
          # exit early if the version does not exist
          curl https://api.github.com/repos/siderolabs/talos/releases/tags/v${{ inputs.version }} \
            --output /dev/null \
            --silent \
            --fail
          
          git clone --branch v${{ inputs.version }} --depth 1 https://github.com/siderolabs/talos.git ./talos.git
          cd ./talos.git && make all GOAMD64=v1 REGISTRY=ghcr.io USERNAME=djeebus PUSH=true

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./talos.git/_out/*"
          body: "# v${{ inputs.version }}"
          commit: "main"
          replacesArtifacts: true
          tag: "${{ inputs.version }}"
