name: build GOAMD64=v1 version of talos

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Talos version

jobs:
  build-release:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - shell: bash
        run: |
          set -e
          
          # exit early if the version does not exist
          curl https://api.github.com/repos/siderolabs/talos/releases/tags/v${{ inputs.version }} \
            --silent \
            --fail
          
          git clone --branch v${{ inputs.version }} --depth 1 https://github.com/siderolabs/talos.git ./talos.git
          cd ./talos.git && make talosctl kernel initramfs GOAMD64=v1

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ./talos.git/_out/*            
